### ISSUE TITLE
please add screen share with audio

### ISSUE THREAD

**Issue by dotnethii** [Shhzdmrz/SignalRCoreWebRTC#1]
Hi Shahzad Mirza please add screen share with audio in SignalRCoreWebRTC thanks

**Comment by Shhzdmrz** [comment]
Hello Masoud,
sure will add soon but if you want to contribute then most welcome.

**Comment by dotnethii** [comment]
this project is very good for Live Stream with asp.net core3.0

   -
      https://github.com/BrennanConroy/StreamR


‫‪Shahzad Mirza‬‏ <‪notifications@github.com‬‏> در تاریخ دوشنبه ۱۰ فوریهٔ
۲۰۲۰ ساعت ۱۱:۵۸ نوشت:‬
