### ISSUE TITLE
Enable video calling 

### ISSUE THREAD

**Issue by WingmanColt** [Shhzdmrz/SignalRCoreWebRTC#3]
How can i enable video calling ?

**Comment by ekhtiari** [comment]
Hi. thanks for you project . can you help me for enable video calling ? thanks

**Comment by sssaff** [comment]
Hi, love the project. Please add video call also, most useful if there can be 2+ people in same video call. Thanks again for great code.

**Comment by YigitGok** [comment]
Hi. Thanks for your project. How can I enable video calling? I found some variables named video, I set them true and when I run project, browser wants me to allow to access my camera but I can't see the video. What can I do?
Thanks. @Shhzdmrz

**Comment by Shhzdmrz** [comment]
Hello, 

You need an video html element inside your page that you will use to display the peer video. Please take a look at [here](https://webrtc.github.io/samples/src/content/capture/video-video/)
