### ISSUE TITLE
Can we Use it in xamarin forms?

### ISSUE THREAD

**Issue by MahdiShamsDev** [Shhzdmrz/SignalRCoreWebRTC#8]
Hello ,
i am wondering if i can use voice call and video call using webRTC in xamarin-form (not webview).
Is it possible?

**Comment by Shhzdmrz** [comment]
Check out these links
[Xamarin.WebRTC](https://alexdunn.org/tag/webrtc/) and [git hub repo](https://github.com/SuavePirate/Xamarin.WebRTC)
