### ISSUE TITLE
Voice calling works perfectly when in same network but no sound when call from other network.

### ISSUE THREAD

**Issue by aslamiqbal** [Shhzdmrz/SignalRCoreWebRTC#9]
Hi,
Thanks for the great work. It's a life-saving project to me.  It works perfectly in the same network. but when I connect my laptop to the internet (mobile data hotspot) then no sound.

**Comment by Shhzdmrz** [comment]
hello,

it is because of the TURN/STUN server configuration that is only for development purpose if you want to use in other network also please buy from [here](https://www.twilio.com/stun-turn/pricing) or from any reliable source and use them. Or you can also create your own TURN/STUN server.
